language: node_js
node_js:
  - v0.12.0
env:
  jwtSecret:
    - secure: "EFyJmYGjsy+LI7o16v7b39loeiXu2AVTwo84yJPPuBNK3cH2FHXMzjVFiAnPkPf6ZttE/6Y7vDyIKUKX3p6GgfT1tpM9hlR+4HR8uUCJa8/epy1z54ANXAiru92ouonof+XtmSoKt8nHBn8982TyuVGiq3GYkPQgx68V3cgRR8CBSMcnA3KFgX1enFpm8RnKwcmOpE5bqnnWNTa0Pw24dOAfq3YM2U68jGQ6o0oGiG+f/R+nGJ2A7WcBRFqRVfnStrqSbSueht18L922PM965l4jP0qR9MJjloBwou2JU8a5vixABuRcuWtCLlL9tKTVcnvF3EFv7zPH71a2v2lWOXyHUkcSNNYzxSY/k+K49oEiamw8yEtqO7aby9lKKj9KDweUzXQ79EPegZqsaqKcsRlzpzLGeMYVRbeogVtHMzIkEtvsFbnjbI1mUgnNRqMboAKS+PEEM3ja2buqy7nznKUPgWOVaBcYkK1ZwTmG+0/gnGE8EYuPrizXZ+pWr9OXYOudRs9C/vLyjFPVY/Xh3H5xsbjObYLz6Xo76Nn0Q5wMqSj53QK3UA1ugX0JsKzXjWICPApo1HQv3lo2EzqMzgYZQxRXXZpk+6pkskxoCyo1/a/uaKvQTyDIcEMd6uKaXEzWecYuRN9MJHnZpOYJUO7uNHRS09J3iuiMftT+zGc="
before_install:
  - npm install tsd --global
install: npm install
script:
  - gulp
  - npm run build